// create a request variable.
var request =new XMLHttpRequest();

//open the request
request.open('GET','https://restcountries.eu/rest/v2/all',true);

//send the request
request.send();

//load the response

request.onload=function(){
	var data=JSON.parse(this.response)
	for(var i in data)
	console.log(data[i].flag)
}

output:
https://restcountries.eu/data/afg.svg
script.js:15 https://restcountries.eu/data/ala.svg
script.js:15 https://restcountries.eu/data/alb.svg
script.js:15 https://restcountries.eu/data/dza.svg
script.js:15 https://restcountries.eu/data/asm.svg
script.js:15 https://restcountries.eu/data/and.svg
script.js:15 https://restcountries.eu/data/ago.svg
script.js:15 https://restcountries.eu/data/aia.svg
script.js:15 https://restcountries.eu/data/ata.svg
script.js:15 https://restcountries.eu/data/atg.svg
script.js:15 https://restcountries.eu/data/arg.svg
script.js:15 https://restcountries.eu/data/arm.svg
script.js:15 https://restcountries.eu/data/abw.svg
script.js:15 https://restcountries.eu/data/aus.svg
script.js:15 https://restcountries.eu/data/aut.svg
script.js:15 https://restcountries.eu/data/aze.svg
script.js:15 https://restcountries.eu/data/bhs.svg
script.js:15 https://restcountries.eu/data/bhr.svg
script.js:15 https://restcountries.eu/data/bgd.svg
script.js:15 https://restcountries.eu/data/brb.svg
script.js:15 https://restcountries.eu/data/blr.svg
script.js:15 https://restcountries.eu/data/bel.svg
script.js:15 https://restcountries.eu/data/blz.svg
script.js:15 https://restcountries.eu/data/ben.svg
script.js:15 https://restcountries.eu/data/bmu.svg
script.js:15 https://restcountries.eu/data/btn.svg
script.js:15 https://restcountries.eu/data/bol.svg
script.js:15 https://restcountries.eu/data/bes.svg
script.js:15 https://restcountries.eu/data/bih.svg
script.js:15 https://restcountries.eu/data/bwa.svg
script.js:15 https://restcountries.eu/data/bvt.svg
script.js:15 https://restcountries.eu/data/bra.svg
script.js:15 https://restcountries.eu/data/iot.svg
script.js:15 https://restcountries.eu/data/umi.svg
script.js:15 https://restcountries.eu/data/vgb.svg
script.js:15 https://restcountries.eu/data/vir.svg
script.js:15 https://restcountries.eu/data/brn.svg
script.js:15 https://restcountries.eu/data/bgr.svg
script.js:15 https://restcountries.eu/data/bfa.svg
script.js:15 https://restcountries.eu/data/bdi.svg
script.js:15 https://restcountries.eu/data/khm.svg
script.js:15 https://restcountries.eu/data/cmr.svg
script.js:15 https://restcountries.eu/data/can.svg
script.js:15 https://restcountries.eu/data/cpv.svg
script.js:15 https://restcountries.eu/data/cym.svg
script.js:15 https://restcountries.eu/data/caf.svg
script.js:15 https://restcountries.eu/data/tcd.svg
script.js:15 https://restcountries.eu/data/chl.svg
script.js:15 https://restcountries.eu/data/chn.svg
script.js:15 https://restcountries.eu/data/cxr.svg
script.js:15 https://restcountries.eu/data/cck.svg
script.js:15 https://restcountries.eu/data/col.svg
script.js:15 https://restcountries.eu/data/com.svg
script.js:15 https://restcountries.eu/data/cog.svg
script.js:15 https://restcountries.eu/data/cod.svg
script.js:15 https://restcountries.eu/data/cok.svg
script.js:15 https://restcountries.eu/data/cri.svg
script.js:15 https://restcountries.eu/data/hrv.svg
script.js:15 https://restcountries.eu/data/cub.svg
script.js:15 https://restcountries.eu/data/cuw.svg
script.js:15 https://restcountries.eu/data/cyp.svg
script.js:15 https://restcountries.eu/data/cze.svg
script.js:15 https://restcountries.eu/data/dnk.svg
script.js:15 https://restcountries.eu/data/dji.svg
script.js:15 https://restcountries.eu/data/dma.svg
script.js:15 https://restcountries.eu/data/dom.svg
script.js:15 https://restcountries.eu/data/ecu.svg
script.js:15 https://restcountries.eu/data/egy.svg
script.js:15 https://restcountries.eu/data/slv.svg
script.js:15 https://restcountries.eu/data/gnq.svg
script.js:15 https://restcountries.eu/data/eri.svg
script.js:15 https://restcountries.eu/data/est.svg
script.js:15 https://restcountries.eu/data/eth.svg
script.js:15 https://restcountries.eu/data/flk.svg
script.js:15 https://restcountries.eu/data/fro.svg
script.js:15 https://restcountries.eu/data/fji.svg
script.js:15 https://restcountries.eu/data/fin.svg
script.js:15 https://restcountries.eu/data/fra.svg
script.js:15 https://restcountries.eu/data/guf.svg
script.js:15 https://restcountries.eu/data/pyf.svg
script.js:15 https://restcountries.eu/data/atf.svg
script.js:15 https://restcountries.eu/data/gab.svg
script.js:15 https://restcountries.eu/data/gmb.svg
script.js:15 https://restcountries.eu/data/geo.svg
script.js:15 https://restcountries.eu/data/deu.svg
script.js:15 https://restcountries.eu/data/gha.svg
script.js:15 https://restcountries.eu/data/gib.svg
script.js:15 https://restcountries.eu/data/grc.svg
script.js:15 https://restcountries.eu/data/grl.svg
script.js:15 https://restcountries.eu/data/grd.svg
script.js:15 https://restcountries.eu/data/glp.svg
script.js:15 https://restcountries.eu/data/gum.svg
script.js:15 https://restcountries.eu/data/gtm.svg
script.js:15 https://restcountries.eu/data/ggy.svg
script.js:15 https://restcountries.eu/data/gin.svg
script.js:15 https://restcountries.eu/data/gnb.svg
script.js:15 https://restcountries.eu/data/guy.svg
script.js:15 https://restcountries.eu/data/hti.svg
script.js:15 https://restcountries.eu/data/hmd.svg
script.js:15 https://restcountries.eu/data/vat.svg
script.js:15 https://restcountries.eu/data/hnd.svg
script.js:15 https://restcountries.eu/data/hkg.svg
script.js:15 https://restcountries.eu/data/hun.svg
script.js:15 https://restcountries.eu/data/isl.svg
script.js:15 https://restcountries.eu/data/ind.svg
script.js:15 https://restcountries.eu/data/idn.svg
script.js:15 https://restcountries.eu/data/civ.svg
script.js:15 https://restcountries.eu/data/irn.svg
script.js:15 https://restcountries.eu/data/irq.svg
script.js:15 https://restcountries.eu/data/irl.svg
script.js:15 https://restcountries.eu/data/imn.svg
script.js:15 https://restcountries.eu/data/isr.svg
script.js:15 https://restcountries.eu/data/ita.svg
script.js:15 https://restcountries.eu/data/jam.svg
script.js:15 https://restcountries.eu/data/jpn.svg
script.js:15 https://restcountries.eu/data/jey.svg
script.js:15 https://restcountries.eu/data/jor.svg
script.js:15 https://restcountries.eu/data/kaz.svg
script.js:15 https://restcountries.eu/data/ken.svg
script.js:15 https://restcountries.eu/data/kir.svg
script.js:15 https://restcountries.eu/data/kwt.svg
script.js:15 https://restcountries.eu/data/kgz.svg
script.js:15 https://restcountries.eu/data/lao.svg
script.js:15 https://restcountries.eu/data/lva.svg
script.js:15 https://restcountries.eu/data/lbn.svg
script.js:15 https://restcountries.eu/data/lso.svg
script.js:15 https://restcountries.eu/data/lbr.svg
script.js:15 https://restcountries.eu/data/lby.svg
script.js:15 https://restcountries.eu/data/lie.svg
script.js:15 https://restcountries.eu/data/ltu.svg
script.js:15 https://restcountries.eu/data/lux.svg
script.js:15 https://restcountries.eu/data/mac.svg
script.js:15 https://restcountries.eu/data/mkd.svg
script.js:15 https://restcountries.eu/data/mdg.svg
script.js:15 https://restcountries.eu/data/mwi.svg
script.js:15 https://restcountries.eu/data/mys.svg
script.js:15 https://restcountries.eu/data/mdv.svg
script.js:15 https://restcountries.eu/data/mli.svg
script.js:15 https://restcountries.eu/data/mlt.svg
script.js:15 https://restcountries.eu/data/mhl.svg
script.js:15 https://restcountries.eu/data/mtq.svg
script.js:15 https://restcountries.eu/data/mrt.svg
script.js:15 https://restcountries.eu/data/mus.svg
script.js:15 https://restcountries.eu/data/myt.svg
script.js:15 https://restcountries.eu/data/mex.svg
script.js:15 https://restcountries.eu/data/fsm.svg
script.js:15 https://restcountries.eu/data/mda.svg
script.js:15 https://restcountries.eu/data/mco.svg
script.js:15 https://restcountries.eu/data/mng.svg
script.js:15 https://restcountries.eu/data/mne.svg
script.js:15 https://restcountries.eu/data/msr.svg
script.js:15 https://restcountries.eu/data/mar.svg
script.js:15 https://restcountries.eu/data/moz.svg
script.js:15 https://restcountries.eu/data/mmr.svg
script.js:15 https://restcountries.eu/data/nam.svg
script.js:15 https://restcountries.eu/data/nru.svg
script.js:15 https://restcountries.eu/data/npl.svg
script.js:15 https://restcountries.eu/data/nld.svg
script.js:15 https://restcountries.eu/data/ncl.svg
script.js:15 https://restcountries.eu/data/nzl.svg
script.js:15 https://restcountries.eu/data/nic.svg
script.js:15 https://restcountries.eu/data/ner.svg
script.js:15 https://restcountries.eu/data/nga.svg
script.js:15 https://restcountries.eu/data/niu.svg
script.js:15 https://restcountries.eu/data/nfk.svg
script.js:15 https://restcountries.eu/data/prk.svg
script.js:15 https://restcountries.eu/data/mnp.svg
script.js:15 https://restcountries.eu/data/nor.svg
script.js:15 https://restcountries.eu/data/omn.svg
script.js:15 https://restcountries.eu/data/pak.svg
script.js:15 https://restcountries.eu/data/plw.svg
script.js:15 https://restcountries.eu/data/pse.svg
script.js:15 https://restcountries.eu/data/pan.svg
script.js:15 https://restcountries.eu/data/png.svg
script.js:15 https://restcountries.eu/data/pry.svg
script.js:15 https://restcountries.eu/data/per.svg
script.js:15 https://restcountries.eu/data/phl.svg
script.js:15 https://restcountries.eu/data/pcn.svg
script.js:15 https://restcountries.eu/data/pol.svg
script.js:15 https://restcountries.eu/data/prt.svg
script.js:15 https://restcountries.eu/data/pri.svg
script.js:15 https://restcountries.eu/data/qat.svg
script.js:15 https://restcountries.eu/data/kos.svg
script.js:15 https://restcountries.eu/data/reu.svg
script.js:15 https://restcountries.eu/data/rou.svg
script.js:15 https://restcountries.eu/data/rus.svg
script.js:15 https://restcountries.eu/data/rwa.svg
script.js:15 https://restcountries.eu/data/blm.svg
script.js:15 https://restcountries.eu/data/shn.svg
script.js:15 https://restcountries.eu/data/kna.svg
script.js:15 https://restcountries.eu/data/lca.svg
script.js:15 https://restcountries.eu/data/maf.svg
script.js:15 https://restcountries.eu/data/spm.svg
script.js:15 https://restcountries.eu/data/vct.svg
script.js:15 https://restcountries.eu/data/wsm.svg
script.js:15 https://restcountries.eu/data/smr.svg
script.js:15 https://restcountries.eu/data/stp.svg
script.js:15 https://restcountries.eu/data/sau.svg
script.js:15 https://restcountries.eu/data/sen.svg
script.js:15 https://restcountries.eu/data/srb.svg
script.js:15 https://restcountries.eu/data/syc.svg
script.js:15 https://restcountries.eu/data/sle.svg
script.js:15 https://restcountries.eu/data/sgp.svg
script.js:15 https://restcountries.eu/data/sxm.svg
script.js:15 https://restcountries.eu/data/svk.svg
script.js:15 https://restcountries.eu/data/svn.svg
script.js:15 https://restcountries.eu/data/slb.svg
script.js:15 https://restcountries.eu/data/som.svg
script.js:15 https://restcountries.eu/data/zaf.svg
script.js:15 https://restcountries.eu/data/sgs.svg
script.js:15 https://restcountries.eu/data/kor.svg
script.js:15 https://restcountries.eu/data/ssd.svg
script.js:15 https://restcountries.eu/data/esp.svg
script.js:15 https://restcountries.eu/data/lka.svg
script.js:15 https://restcountries.eu/data/sdn.svg
script.js:15 https://restcountries.eu/data/sur.svg
script.js:15 https://restcountries.eu/data/sjm.svg
script.js:15 https://restcountries.eu/data/swz.svg
script.js:15 https://restcountries.eu/data/swe.svg
script.js:15 https://restcountries.eu/data/che.svg
script.js:15 https://restcountries.eu/data/syr.svg
script.js:15 https://restcountries.eu/data/twn.svg
script.js:15 https://restcountries.eu/data/tjk.svg
script.js:15 https://restcountries.eu/data/tza.svg
script.js:15 https://restcountries.eu/data/tha.svg
script.js:15 https://restcountries.eu/data/tls.svg
script.js:15 https://restcountries.eu/data/tgo.svg
script.js:15 https://restcountries.eu/data/tkl.svg
script.js:15 https://restcountries.eu/data/ton.svg
script.js:15 https://restcountries.eu/data/tto.svg
script.js:15 https://restcountries.eu/data/tun.svg
script.js:15 https://restcountries.eu/data/tur.svg
script.js:15 https://restcountries.eu/data/tkm.svg
script.js:15 https://restcountries.eu/data/tca.svg
script.js:15 https://restcountries.eu/data/tuv.svg
script.js:15 https://restcountries.eu/data/uga.svg
script.js:15 https://restcountries.eu/data/ukr.svg
script.js:15 https://restcountries.eu/data/are.svg
script.js:15 https://restcountries.eu/data/gbr.svg
script.js:15 https://restcountries.eu/data/usa.svg
script.js:15 https://restcountries.eu/data/ury.svg
script.js:15 https://restcountries.eu/data/uzb.svg
script.js:15 https://restcountries.eu/data/vut.svg
script.js:15 https://restcountries.eu/data/ven.svg
script.js:15 https://restcountries.eu/data/vnm.svg
script.js:15 https://restcountries.eu/data/wlf.svg
script.js:15 https://restcountries.eu/data/esh.svg
script.js:15 https://restcountries.eu/data/yem.svg
script.js:15 https://restcountries.eu/data/zmb.svg
script.js:15 https://restcountries.eu/data/zwe.svg